server:
  port: 8080

spring:
  application:
    name: Yacht
  config:
    import: optional:file:.env[.properties]

mq:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}
