package HooYah.Yacht.part.service;

import HooYah.Yacht.part.domain.Part;
import HooYah.Yacht.part.dto.request.AddPartDto;
import HooYah.Yacht.repair.service.RepairService;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@RequiredArgsConstructor
@Service
public class CreatePartService {

    private final PartService partService;
    private final RepairService repairService;

    public Part addPart(AddPartDto dto, Long userId) {
        Part newPart = partService.addPart(dto.getYachtId(), dto, userId);

        if(dto.getLastRepair() != null)
            repairService.addRepair(newPart.getId(), "autoGenerated", dto.getLastRepair(), userId);

        return newPart;
    }

    public List<Part> addPartList(Long yachtId, List<AddPartDto> dtoList) {
        List<Part> createdPartList = partService.addPartList(yachtId, dtoList);

        List<Part> repairAddPartList = new ArrayList<>();
        List<OffsetDateTime> repairAddRepairList = new ArrayList<>();

        for(int i = 0; i < createdPartList.size(); i++) {
            if(dtoList.get(i).getLastRepair() != null) { // 이거 생각보다 위험하다 :: repair에 필요한 값이 추가 된다면 Part값이 수정되어야함 --> 다른 domain의 값이 dto에 침범함
                OffsetDateTime repairDate = dtoList.get(i).getLastRepair();

                repairAddRepairList.add(repairDate);
                repairAddPartList.add(createdPartList.get(i));
            }
        }

        repairService.addRepairList(repairAddPartList, repairAddRepairList);

        return createdPartList;
    }

}
