package HooYah.Yacht.service;

import HooYah.Yacht.domain.Alarm;
import HooYah.Yacht.repository.AlarmRepository;
import HooYah.Yacht.domain.Calendar;
import HooYah.Yacht.domain.CalendarType;
import HooYah.Yacht.repository.CalendarRepository;
import java.time.OffsetDateTime;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class CalendarAlarmAutoGeneratorService {

    private final CalendarRepository calendarRepository;
    private final AlarmRepository alarmRepository;

    @Transactional
    public void generate(Long partId, Long yachtId, OffsetDateTime nextRepairDate) {
        if(partId == null || nextRepairDate == null)
            return;

        generateCalendar(partId, yachtId, nextRepairDate);
        generateAlarm(partId, yachtId, nextRepairDate);
    }

    private void generateCalendar(Long partId, Long yachtId, OffsetDateTime nextRepairDate) {
        // 동일 part의 켈린더 삭제 (생성 날짜 이전의 자동 생성된 Calendar 모두 삭제)
        List<Calendar> oldCalendarList = calendarRepository.findByPartId(partId);

        List<Calendar> autoGeneratedCalendarList = oldCalendarList
                .stream()
                .filter(c->c.getStartDate().isBefore(nextRepairDate)) // 생성 calendar 보다 이전의
                .filter(c->!c.isCompleted())
                .filter(c->!c.isByUser()) // user가 수정하지 않은
                .toList(); // domain 규칙들에 속함 service에서 처리할 규칙이 아님!

        calendarRepository.deleteAll(autoGeneratedCalendarList);

        calendarRepository.save(
            Calendar
                .builder()
                .content("Auto Generated")
                .type(CalendarType.PART)
                .startDate(nextRepairDate)
                .endDate(nextRepairDate)
                .partId(partId)
                .yachtId(yachtId)
                .buildByAuto()
        );

    }

    private void generateAlarm(Long partId, Long yachtId, OffsetDateTime nextRepairDate) {
        // 이전 part의 alarm을 삭제함
        alarmRepository.deleteAllByPartId(partId);

        Alarm alarm = Alarm
                .builder()
                .partId(partId)
                .yachtId(yachtId)
                .date(nextRepairDate)
                .build();

        alarmRepository.save(alarm);
    }

}
