package HooYah.Yacht.service;

import HooYah.Yacht.domain.Calendar;
import HooYah.Yacht.domain.CalendarType;
import HooYah.Yacht.domain.CalendarUser;
import HooYah.Yacht.dto.request.CalendarCreateRequest;
import HooYah.Yacht.dto.request.CalendarUpdateRequest;
import HooYah.Yacht.dto.response.CalendarInfo;
import HooYah.Yacht.event.CalendarCompleteEvent;
import HooYah.Yacht.event.CreateEvent;
import HooYah.Yacht.event.DeletedEvent;
import HooYah.Yacht.excetion.CustomException;
import HooYah.Yacht.excetion.ErrorCode;
import HooYah.Yacht.publisher.MessagePublisher;
import HooYah.Yacht.repository.CalendarRepository;
import HooYah.Yacht.repository.CalendarUserRepository;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.support.TransactionTemplate;

@Service
@RequiredArgsConstructor
public class CalendarService {

    private final CalendarRepository calendarRepository;

    private final AskService askService;

    private final MessagePublisher<CreateEvent> calendarCreateMessagePublisher;
    private final MessagePublisher<CalendarCompleteEvent> calendarCompleteMessagePublisher;
    private final MessagePublisher<DeletedEvent> calendarDeleteMessagePublisher;

    private final TransactionTemplate transactionTemplate;
    private final CalendarUserRepository calendarUserRepository;

    private Logger logger = LoggerFactory.getLogger(this.getClass());

    public CalendarInfo createCalendarByUser(CalendarCreateRequest dto, Long userId) {
        // validate dto.getPartId, YachtUser, userList
        Object yachtInfo = askService.validateYachtUser(dto.getYachtId(), userId);
        Object partInfo = null;
        List referenceUserInfoList = askService.getUserInfoList(dto.getUserList());

        // if (type == Part) delete old calendar
        if(dto.getType() == CalendarType.PART) {
            partInfo = askService.validatePart(dto.getPartId());
            // 동일 part의 켈린더 삭제 (생성 날짜 이전의 자동 생성된 Calendar 모두 삭제)
            List<Calendar> oldCalendarList = calendarRepository.findByPartId(dto.getPartId());

            List<Calendar> autoGeneratedCalendarList = oldCalendarList
                    .stream()
                    .filter(c->c.getStartDate().isBefore(dto.getStartDate())) // 생성 calendar 보다 이전의
                    .filter(c->!c.isByUser()) // user가 수정하지 않은
                    .filter(c->!c.isCompleted())
                    .toList(); // domain 규칙들에 속함 service에서 처리할 규칙이 아님!

            calendarRepository.deleteAll(autoGeneratedCalendarList);
        }
        Calendar newCalendar = createCalendarDomain(dto);

        // Publish Events
        // calendarCreateMessagePublisher.publish(new CreateEvent(newCalendar.getId(), userId));

        if(newCalendar.isCompletedNow()) {
            calendarCompleteMessagePublisher.publish(new CalendarCompleteEvent(newCalendar.getId(), userId, newCalendar.getPartId(), newCalendar.getEndDate(), newCalendar.getContent()));
            // createNewRepair(newCalendar, userId);
        }

        return CalendarInfo.of(newCalendar, partInfo, yachtInfo, referenceUserInfoList);
    }

    @Transactional
    public Calendar createCalendarDomain(CalendarCreateRequest dto) {
        // calendar 생성
        Calendar newCalendar = Calendar
                .builder()
                .startDate(dto.getStartDate())
                .endDate(dto.getEndDate())
                .type(dto.getType())
                .partId(dto.getPartId())
                .content(dto.getContent())
                .review(dto.getReview())
                .yachtId(dto.getYachtId())
                .isCompleted(dto.getCompleted())
                .buildByUser();

        // calendar 참조인 처리
        newCalendar.setCalendarUsers(dto.getUserList());

        return calendarRepository.save(newCalendar);
    }

    public Calendar updateCalendar(Long id, CalendarUpdateRequest dto, Long userId) {
        Calendar calendar = calendarRepository.findById(id)
                .orElseThrow(()-> new CustomException(ErrorCode.NOT_FOUND));

        askService.validateYachtUser(calendar.getYachtId(), userId);

        calendar = updateCalendarDomain(calendar, dto);

        // Publish CompleteEvent only if completedNow
        if(calendar.isCompletedNow()) {
            calendarCompleteMessagePublisher.publish(new CalendarCompleteEvent(calendar.getId(), userId, calendar.getPartId(), calendar.getEndDate(), calendar.getContent()));
            // createNewRepair(calendar, userId);
        }

        return calendar;
    }

    @Transactional
    public Calendar updateCalendarDomain(Calendar calendar, CalendarUpdateRequest request) {
        calendar.updateDate(request.getStartDate(), request.getEndDate());
        calendar.update(request.getPartId(), request.getContent(), request.getReview());
        calendar.updateComplete(request.getCompleted()); // 실행의 순서는 domain 로직에 해당한다 -> entity 함수에 넣을 것
        calendar.setByUserTrue();

        // if 참조인이 변경되었다면,
        if(request.getUserList() != null && !request.getUserList().isEmpty()) {
            // verify userIdList
            askService.getUserInfoList(request.getUserList());
            calendar.setCalendarUsers(request.getUserList());
        }
        calendarRepository.save(calendar);
        return calendar;

    }

    public CalendarInfo getCalendar(Long id, Long userId) {
        Calendar calendar = calendarRepository.findById(id)
                .orElseThrow(()->new CustomException(ErrorCode.NOT_FOUND));

        // validate yacht user
        Object yachtInfo = askService.validateYachtUser(calendar.getYachtId(), userId);
        List userInfoList = askService.getUserInfoList(calendar.getCalenderUserIdList());

        Object partInfo = null;
        if(calendar.getPartId() != null)
            partInfo = askService.validatePart(calendar.getPartId());

        // 예전 로직 변경 : return List<Part> :: all part data by yacht -> do not return
//        List<Part> parts = null;
//        if (yacht != null) {
//            parts = partRepository.findPartListByYacht(yacht.getId()); // 요트의 모든 part list를 왜 여기서 반환하는 거지?
//        }

        return CalendarInfo.of(calendar, partInfo, yachtInfo, userInfoList);
    }

    // get calendar list by List<Yacht>
    public List<CalendarInfo> getCalendars(Long userId) {
        List<Long> yachtIdList = askService.yachtListInMemory(userId);

        // List<Long :: YachtId> 기준 모든 Calendar 조회 (날짜 순)
        List<Calendar> calendars = calendarRepository.findAllByYachtOrderByStartDate(yachtIdList);

        // select other domain dtos...
        List<List<?>> userInfoList = askService.getUserInfoListList(
                calendars
                    .stream()
                    .map((c)-> c.getCalendarUsers().stream().map(CalendarUser::getUserId).toList())
                    .toList()
        );
        List<?> partInfoList = askService.getPartInfoList(
                calendars
                        .stream()
                        .map(Calendar::getPartId) // null 포함 가능합 --> 상관없음
                        .toList()
        );
        List<?> yachtInfoList = askService.getYachtInfoList(yachtIdList);
        Map<Long, Object> yachtInfoMap = new HashMap<>();
        for(int i = 0; i < yachtIdList.size(); i++)
            yachtInfoMap.put(yachtIdList.get(i), yachtInfoList.get(i));

        List<?> sortedYachtInfoList = calendars
                .stream()
                .map(c->yachtInfoMap.get(c.getYachtId()))
                .toList();

        return CalendarInfo.of(calendars, partInfoList, sortedYachtInfoList, userInfoList);
    }

    public void deleteCalendar(Long id, Long userId) {
        Calendar calendar = calendarRepository.findById(id)
                .orElseThrow(()->new CustomException(ErrorCode.NOT_FOUND));
        askService.validateYachtUser(calendar.getYachtId(), userId);

        calendarRepository.delete(calendar);

        // Publish DeletedEvent (Constructor order: id, userId)
        // calendarDeleteMessagePublisher.publish(new DeletedEvent(id, userId));
    }

    // event listener
    @Transactional
    public void deleteCalendarUserByUserId(Long userId) {
        calendarUserRepository.deleteAllByUserId(userId);
    }

    @Transactional
    public void deleteByYachtId(Long yachtId) {
        calendarRepository.deleteAllByYachtId(yachtId);

        // publisher.publish()
    }

    @Transactional
    public void deleteByPartId(Long partId) {
        calendarRepository.deleteAllByPartId(partId);

        // publisher.publish()
    }

}


